name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Generate commit hash tag
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v5
      with:
        push: true
        build-args: |
          GIT_COMMIT=${{ steps.vars.outputs.sha_short }}
        tags: |
          micosa79/atlas:latest
          micosa79/atlas:${{ steps.vars.outputs.sha_short }}

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}